name: Release QMK Firmware

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  build:
    uses: ./.github/workflows/build-firmware.yml
    with:
      keyboard: ${{ matrix.keyboard }}
      keymap: ${{ matrix.keymap }}
      side: ${{ matrix.side }}
    strategy:
      matrix:
        keyboard: [ svalboard/trackpoint, svalboard, svalboard/trackball ]
        keymap: [ vial ]
        side: [ left, right ]
